### PR TITLE
Fix: `@import` url() error in dependency resolver

### LINKED ISSUE #2595: @import url() not working
When I try to import Google Fonts or any external URL via `@import url('https://...')`, it throws an error: `Cannot read property 'isNull' of undefined`. 

### Example:
```
const stylus = require('stylus');
stylus(`@import url('https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Montserrat|Inconsolata:400,700&display=swap')`).deps();
```

It seems to be related to: https://github.com/stylus/stylus/blob/59bc665db295981d4e3f702e7275c5589a3c6d15/lib/visitor/deps-resolver.js#L113

### Workaround:
```
@css {
    @import url('https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Montserrat|Inconsolata:400,700&display=swap')`);
}
```
That way Stylus doesn't compile it and the error is not thrown.

### The original issue:
https://github.com/vitejs/vite/issues/3984

### PR DESCRIPTION
**Pull request by groenroos**
**What**: Fixes #2595 

**Why**: Because `@import url()` returns an error for the `.deps()` / `--deps` flag

**How**: Add a check to `DepsResolver.prototype.visitImport` to skip `url()` imports from dependency resolver, and thus from dependency lists

**Checklist**:

- [ ] Documentation
- [x] Unit Tests
- [x] Code complete

**Comments**
- It may be argued whether `url()` should or should not be included in the deps list (the documentation is not explicit about this) - however I've opted to skip them from the deps list, since they'll be almost necessarily external to the consumer codebase
- Replaces #2627, as that solution causes other bugs in unit tests

### CODE REVIEW

**Review by iChenLei — COMMENTED** [review]
> https://developer.mozilla.org/en-US/docs/Web/CSS/@import#examples

Awesome pull request, thank you. I have a small request, can you add more complex unit test for this bugfix ? Current test case looks like function spec unit test, we can add more e2e-like tests, for example:

Input:
```styl
// import.url.styl
@import url('https://fonts.googleapis.com/css)
@import xxx;

// more code
```

Output:
```styl
// import.url.css
@import url('https://fonts.googleapis.com/css)

// gen code
```

There are many e2e-like tests in `stylus/test/cases/*`, more unit test cases is always a good thing, thank you again.

**Comment by groenroos** [comment]
@iChenLei Thanks for the review!

I reckoned the e2e tests were already covered by `import.include.resolver.absolute.styl`:

https://github.com/stylus/stylus/blob/9cb7635af60bf918ed8c2a990efd251e2e825975/test/cases/import.include.resolver.absolute.styl#L1-L4

In any case, this issue seems to be specific to generating the deps list with the `--deps` flag or the `.deps()` method - this issue seemed to never affect just parsing Stylus into CSS itself.

Let me know if there's some specific case that I should cover!

File: lib/visitor/deps-resolver.js [hunk 1]
```diff
@@ -110,6 +110,9 @@ DepsResolver.prototype.visitCall = function(call) {
  */
 
 DepsResolver.prototype.visitImport = function(node) {
+  // If it's a url() call, skip
```
Comment (iChenLei) [inline lib/visitor/deps-resolver.js:113]: LGTM

**Review by iChenLei — APPROVED** [review]

**Comment by groenroos** [comment]
@iChenLei Let me know if there is anything further to be done for this PR! I don't have write access so I cannot merge it myself.

**Comment by iChenLei** [comment]
@groenroos Check your permission please, I think you can merge this pr by yourself now. If encount any issue please @ me again. Thanks! Anyway, every pull request need peer review ! We should ensure pull request's quality.
