### PR TITLE
Pass strict mode. Fixes #1922

### LINKED ISSUE #1922: Pass strict mode
Stylus should not fail to compile in strict mode (--use_strict).
This requires removing the octal values in the code and changing the variable name "package" to something else, e.g. "pkg".

### PR DESCRIPTION
**Pull request by blitzprog**
#1922

### CODE REVIEW

File: lib/functions/index.js [hunk 1]
```diff
@@ -1131,7 +1131,8 @@ exports.match = function match(pattern, val){
   [].slice.call(arguments).forEach(function(expr){
     expr = utils.unwrap(expr);
     if (!expr.nodes.length) return;
-    console.log('\033[90minspect:\033[0m %s', expr.toString().replace(/^\(|\)$/g, ''));
+    var _033 = parseInt('033', 8);
+    console.log(_033 + '[90minspect:' + _033 + '[0m %s', expr.toString().replace(/^\(|\)$/g, ''));
```
Comment (Panya) [inline lib/functions/index.js]: There should be `\u001b` instead of `\033`. See http://etutorials.org/Programming/actionscript/Appendix+A.+Unicode+Escape+Sequences+for+Latin+1+Characters/

File: lib/visitor/evaluator.js [hunk 2]
```diff
@@ -1525,7 +1525,8 @@ Evaluator.prototype.castable = function(expr){
 
 Evaluator.prototype.warn = function(msg){
   if (!this.warnings) return;
-  console.warn('\033[33mWarning:\033[0m ' + msg);
+  var _033 = parseInt('033', 8);
+  console.warn(_033 + '[33mWarning:' + _033 + '[0m ' + msg);
```
Comment (Panya) [inline lib/visitor/evaluator.js]: same as above

**Comment by Panya** [comment]
Thanks!
